# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/databases
Accept: application/json

###

GET http://127.0.0.1:8000/collections/health_data
Accept: application/json

###

GET http://127.0.0.1:8000/documents/health_data/aw_data
Accept: application/json

###

GET http://127.0.0.1:8000/documents/health_data/aw_data/filter?age=20
Accept: application/json

###

GET http://127.0.0.1:8000/documents/health_data/aw_data/projection?age=20
Accept: application/json
